### ISSUE TITLE
Add "intermediate" volume

### ISSUE THREAD

**Issue by woiza** [linuxserver/docker-nzbget-armhf#10]
Could you please add another volume ("intermediate") to you container? The idea is to store config data in a docker volume, intermediate downloads on a rather fast drive and downloads on another slow but "big" drive. Nzbget recommends puting InterDir and DestDir on seperate hard drives for best unpacking performance.
I am opening this issue here, but I think it would be useful for your x86 container as well.

**Comment by sparklyballs** [comment]
you can add any volume you want directly from the run line 

eg

`-v /some/mystical/other/drive:/interdir`

**Comment by sparklyballs** [comment]
rather than specifically add another mount point i think our best way forward is a supplemental note in the README

**Comment by woiza** [comment]
Thanks, will try that tonight.
